### ISSUE TITLE
Deleting user inbox

### ISSUE THREAD

**Issue by daljit3** [testdrivenio/django-channels-example#2]
Should the line 66 in `chat/consumers.py` have `group_discard()` instead of `group_add()` in the `disconnect()` method? (for deleting the user inbox?)

**Comment by anibaligh** [comment]
Could you explain why you use async_to_sync(self.channel_layer.**group_add**) on line 66 of chat/consumers.py, please?

**Comment by duplxey** [comment]
You're right @daljit3, the line 66 in `chat/consumers.py` should be `group_discard()` since we want to delete the user inbox.

@anibaligh Look at @daljit3's comment.
